name: Cross browser testing Github Actions
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.1

      - name: Install wdio
        run: npm install   
      - name: Allure-reporter install
        run:  npm install @wdio/allure-reporter --save-dev
      - name: Allure-commandline install
        run:  npm i allure-commandline
      - name: Geckodriver install
        run:  npm install geckodriver --save-dev
      - name: Start crossbrowser test
        run: npm run test_github

      - name: Upload results
        uses: actions/upload-artifact@v3.1.0
        with:
          name: allure-report
          path: allure-report
          
      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          branch: gh-pages
          folder: allure-report
